### ISSUE TITLE
#SEO 对于UGC生成的出站链接都应该添加`nofollow`

### ISSUE THREAD

**Issue by madawei2699** [hackershare/hackershare#109]
查看了下生成的HTML代码，现在的做法是对于用户分享的bookmark都通过生成一个/goto/链接做302跳转。这会带来一些SEO问题：

因为搜索引擎抓取时发现/goto/链接做了302跳转到新的地址了，所以它会继续去抓取目标页面的内容，然后收录索引，这就会产生重复内容的问题，通过在Google执行`site:https://hackershare.dev/ goto/ bmpi`就会发现它已经收录了两篇文章，并且用的链接是hackershare的链接，但是内容和[https://www.bmpi.dev](https://www.bmpi.dev)博客的链接内容完全一样，由于博客的内容要早于hackershare的内容，Google就会认为hackershare在复制其他站的内容，从而对hackershare做一些惩罚，可能会标记为垃圾站。

最佳的做法就是给/goto/链接做一个`nofollow`的标签属性，这方面可以参考Hacker News的做法，一般的分享站或者UGC的站都会对出站链接做`nofollow`。

**Comment by hooopo** [comment]
看了一下，确实302之后会存在问题，但好像nofollow解决不了这个问题。

nofollow解决的是pr传递问题，不解决页面收录。

看了一下，hackernews直接使用的普通link，未做任何处理，没有nofollow合302跳转。

收录问题应该no-index就可以解决，参考了一下producthunt：

```
curl -vv https://www.producthunt.com/r/dfe05604fa880b
*   Trying 104.18.231.83...
* TCP_NODELAY set
^C
[~/w/hypercable/hypercable] (main) 9h44m $ curl -vv https://www.producthunt.com/r/dfe05604fa880b
*   Trying 104.18.231.83...
* TCP_NODELAY set
* Connected to www.producthunt.com (104.18.231.83) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Aug  5 00:00:00 2020 GMT
*  expire date: Aug  5 12:00:00 2021 GMT
*  subjectAltName: host "www.producthunt.com" matched cert's "*.producthunt.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fab07806c00)
> GET /r/dfe05604fa880b HTTP/2
> Host: www.producthunt.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 301
< date: Mon, 25 Jan 2021 03:25:06 GMT
< content-type: text/html; charset=utf-8
< set-cookie: __cfduid=df8016fd3a1fd9bdbca6c0fe433f0b8431611545106; expires=Wed, 24-Feb-21 03:25:06 GMT; path=/; domain=.producthunt.com; HttpOnly; SameSite=Lax
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< x-robots-tag: noindex
< location: https://zodier.io/en?source=producthunt&ref=producthunt
< cache-control: no-cache
< set-cookie: visitor_id=8a7205f2-7fa6-4e56-bbfc-d4b2a17c4392; path=/; expires=Fri, 25 Jan 2041 03:25:06 GMT; Secure; SameSite=None
< set-cookie: track_code=031ada0d10; path=/; expires=Fri, 25 Jan 2041 03:25:06 GMT; Secure; SameSite=None
< set-cookie: csrf_token=QpTNDTZTvvwzRWOnrXl53hVy3rbeo7XtVBRI7pbrUV4aEqTp3QUQk9O5dMI%2BhcWdp2fGSoXFOqDKbnkpAJ0N7Q%3D%3D; path=/; expires=Fri, 25 Jan 2041 03:25:06 GMT; Secure; SameSite=None
< set-cookie: _producthunt_session_production=bVl5a2JJVzBmZEtNNG1QTnlvQlZMUDFhT2R4OW5DRGlKYm5qdTh1R3V0ejlGQUJVNHB0bHhxTFlielZXS2Z1R2dMbXNOdHZ2ZmQ2SXp2RStMTmtFdkxPaE1HK2Y0RUI5SEFkMEloM2RFUHRWTlVYSGUzMDlhdGwxcWpvN3lsay9Gb21PRGtVc3hua2FDUUhCWlhuOThnPT0tLXk0YVQzR1M2Z2IvbUc0K1ZXTE1sMnc9PQ%3D%3D--19d390493805b00555c7997d5327bec9358f0703; domain=.producthunt.com; path=/; expires=Thu, 20 May 2021 21:11:45 GMT; HttpOnly; Secure; SameSite=None
< x-request-id: 9f14621a-9fa1-424d-a438-496ee6ac9613
< x-runtime: 0.013654
< cf-cache-status: DYNAMIC
< cf-request-id: 07d92bee530000ed23d5067000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< strict-transport-security: max-age=2592000; includeSubDomains; preload
< server: cloudflare
< cf-ray: 616ee2908879ed23-SJC
<
* Connection #0 to host www.producthunt.com left intact
<html><body>You are being <a href="https://zodier.io/en?source=producthunt&amp;ref=producthunt">redirected</a>.</body></html>
```

加个 x-robots-tag: noindex 头就可以了

**Comment by madawei2699** [comment]
> 看了一下，确实302之后会存在问题，但好像nofollow解决不了这个问题。
> 
> nofollow解决的是pr传递问题，不解决页面收录。
> 
> hackernews直接使用的普通link，未做任何处理，没有nofollow合302跳转。
> 
> 收录问题应该no-index就可以解决，参考了一下producthunt：
> 
> ```
> curl -vv https://www.producthunt.com/r/dfe05604fa880b
> *   Trying 104.18.231.83...
> * TCP_NODELAY set
> ^C
> [~/w/hypercable/hypercable] (main) 9h44m $ curl -vv https://www.producthunt.com/r/dfe05604fa880b
> *   Trying 104.18.231.83...
> * TCP_NODELAY set
> * Connected to www.producthunt.com (104.18.231.83) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/cert.pem
>   CApath: none
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS change cipher, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
> * ALPN, server accepted to use h2
> * Server certificate:
> *  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
> *  start date: Aug  5 00:00:00 2020 GMT
> *  expire date: Aug  5 12:00:00 2021 GMT
> *  subjectAltName: host "www.producthunt.com" matched cert's "*.producthunt.com"
> *  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
> *  SSL certificate verify ok.
> * Using HTTP2, server supports multi-use
> * Connection state changed (HTTP/2 confirmed)
> * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> * Using Stream ID: 1 (easy handle 0x7fab07806c00)
> > GET /r/dfe05604fa880b HTTP/2
> > Host: www.producthunt.com
> > User-Agent: curl/7.54.0
> > Accept: */*
> >
> * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
> < HTTP/2 301
> < date: Mon, 25 Jan 2021 03:25:06 GMT
> < content-type: text/html; charset=utf-8
> < set-cookie: __cfduid=df8016fd3a1fd9bdbca6c0fe433f0b8431611545106; expires=Wed, 24-Feb-21 03:25:06 GMT; path=/; domain=.producthunt.com; HttpOnly; SameSite=Lax
> < x-frame-options: SAMEORIGIN
> < x-xss-protection: 1; mode=block
> < x-content-type-options: nosniff
> < x-robots-tag: noindex
> < location: https://zodier.io/en?source=producthunt&ref=producthunt
> < cache-control: no-cache
> < set-cookie: visitor_id=8a7205f2-7fa6-4e56-bbfc-d4b2a17c4392; path=/; expires=Fri, 25 Jan 2041 03:25:06 GMT; Secure; SameSite=None
> < set-cookie: track_code=031ada0d10; path=/; expires=Fri, 25 Jan 2041 03:25:06 GMT; Secure; SameSite=None
> < set-cookie: csrf_token=QpTNDTZTvvwzRWOnrXl53hVy3rbeo7XtVBRI7pbrUV4aEqTp3QUQk9O5dMI%2BhcWdp2fGSoXFOqDKbnkpAJ0N7Q%3D%3D; path=/; expires=Fri, 25 Jan 2041 03:25:06 GMT; Secure; SameSite=None
> < set-cookie: _producthunt_session_production=bVl5a2JJVzBmZEtNNG1QTnlvQlZMUDFhT2R4OW5DRGlKYm5qdTh1R3V0ejlGQUJVNHB0bHhxTFlielZXS2Z1R2dMbXNOdHZ2ZmQ2SXp2RStMTmtFdkxPaE1HK2Y0RUI5SEFkMEloM2RFUHRWTlVYSGUzMDlhdGwxcWpvN3lsay9Gb21PRGtVc3hua2FDUUhCWlhuOThnPT0tLXk0YVQzR1M2Z2IvbUc0K1ZXTE1sMnc9PQ%3D%3D--19d390493805b00555c7997d5327bec9358f0703; domain=.producthunt.com; path=/; expires=Thu, 20 May 2021 21:11:45 GMT; HttpOnly; Secure; SameSite=None
> < x-request-id: 9f14621a-9fa1-424d-a438-496ee6ac9613
> < x-runtime: 0.013654
> < cf-cache-status: DYNAMIC
> < cf-request-id: 07d92bee530000ed23d5067000000001
> < expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> < strict-transport-security: max-age=2592000; includeSubDomains; preload
> < server: cloudflare
> < cf-ray: 616ee2908879ed23-SJC
> <
> * Connection #0 to host www.producthunt.com left intact
> <html><body>You are being <a href="https://zodier.io/en?source=producthunt&amp;ref=producthunt">redirected</a>.</body></html>
> ```
> 
> 加个 x-robots-tag: noindex 头就可以了

已经被收录的可以添加noindex，新的内容只需要nofollow即可。

**Comment by madawei2699** [comment]
hacker news对信任的站没有nofollow，但是对不信任的站是有nofollow的，你可以在上面找找那种一般的站的链接，都是nofollow

**Comment by hooopo** [comment]
> hacker news对信任的站没有nofollow，但是对不信任的站是有nofollow的，你可以在上面找找那种一般的站的链接，都是nofollow

和域名没有关系，只和point有关系，上面都说了nofollow只解决PR问题，不解决收录问题。

**Comment by madawei2699** [comment]
和point有关系是在哪里有介绍啊，如果是和point有关系那这个设计真的很妙了。nofollow是对出站链接不传递pr，你这个goto链接是站内，的确需要noindex移除这种收录或者加canoinical来标志原文地址。

Hooopo <notifications@github.com>于2021年1月25日 周一上午11:37写道：

**Comment by hooopo** [comment]
![image](https://user-images.githubusercontent.com/63877/105661248-f3863200-5f07-11eb-9f4d-d39549832c08.png)
![image](https://user-images.githubusercontent.com/63877/105661295-0b5db600-5f08-11eb-87fc-20265a74ed15.png)
同样的域名，我提交的，5point的有nofollow，38point的没有

**Comment by hooopo** [comment]
https://news.ycombinator.com/item?id=21730921

**Comment by madawei2699** [comment]
巧妙的设计，学习了，谢谢！

Hooopo <notifications@github.com>于2021年1月25日 周一下午12:30写道：

**Comment by hooopo** [comment]
fixed https://github.com/hackershare/hackershare/commit/f6c1faee4a04262ede8ced5dcefa721e307e4305
