### ISSUE TITLE
preset rss list

### ISSUE THREAD

**Issue by hooopo** [hackershare/hackershare#58]
## Ruby

* https://blog.saeloun.com/feed.xml
* http://www.rubyinside.com/
* http://www.rubyflow.com/rss
* http://rubyland.news/
* https://sandimetz.com/blog?format=rss
* http://tenderlovemaking.com/atom.xml
* https://www.mikeperham.com/index.xml
* https://weblog.rubyonrails.org/feed/atom.xml
* https://blog.arkency.com/feed.xml
* https://schneems.com/feed.xml
* https://about.gitlab.com/atom.xml
* https://hashrocket.com/blog/posts.rss

## rust

* https://this-week-in-rust.org/
* https://blog.rust-lang.org/feed.xml

## elixir

* https://feeds.feedburner.com/digest-elixir

## postgres

* https://planet.postgresql.org/rss20.xml
* https://www.2ndquadrant.com/en/blog/
* http://www.postgresql-blog.com/feed/
* https://www.highgo.ca/blog/

**Comment by songhuangcn** [comment]
https://www.raychase.net/feed

**Comment by hooopo** [comment]
https://remoteok.io/remote-jobs.rss

**Comment by hooopo** [comment]
https://weekly.statuscode.com/

**Comment by bindiry** [comment]
http://www.ruanyifeng.com/blog/atom.xml

**Comment by songhuangcn** [comment]
https://www.mikeperham.com/index.xml
https://blog.arkency.com/feed.xml
https://weblog.rubyonrails.org/feed/atom.xml
https://blog.rust-lang.org/feed.xml

除了这几个解析失败，上面其他的都添加到网站解析了。功能使用看这个 MR:
https://github.com/hackershare/hackershare/pull/73

后面大家有新的源可以继续提出来，我会再添加上去

**Comment by songhuangcn** [comment]
用户可以自己提交 RSS 源了，功能介绍看这个 MR: https://github.com/hackershare/hackershare/pull/86

该 issue 不需要了。
