### ISSUE TITLE
Problem: can follow oneself

### ISSUE THREAD

**Issue by foreseaz** [hackershare/hackershare#67]
Is it a bug to be able to follow oneself on the profile page? Screenshots as following.

![image](https://user-images.githubusercontent.com/5697641/93860214-51ec9b00-fcf1-11ea-880a-f5497e998081.png)

![image](https://user-images.githubusercontent.com/5697641/93860155-3aadad80-fcf1-11ea-8280-d28fe921770e.png)

**Comment by hooopo** [comment]
It's a feature 🐶
