### ISSUE TITLE
sharable url

### ISSUE THREAD

**Issue by hooopo** [hackershare/hackershare#80]
https://hackershare.dev/cn?query=%E7%BC%96%E7%A8%8B

这个url生成应该用 https://hackershare.dev/cn//bookmarks/?query=%E7%BC%96%E7%A8%8B

登录时分享出去，不登录的人打开不对

**Comment by hooopo** [comment]
👏
还有排序和标签过滤，suggest那里

**Comment by songhuangcn** [comment]
@hooopo 修复了，请再确认一下。

**Comment by hooopo** [comment]
可以了🌟
